version: 0.2
env:
  parameter-store:
    DATABASE_USER: "DATABASE_USER"
    DATABASE_NAME: "DATABASE_NAME"
    DATABASE_PASSWORD: "DATABASE_PASSWORD"
    DATABASE_ENDPOINT: "DATABASE_ENDPOINT"
    AWS_REGION: "REGION_AWS"
    AWS_ACCOUNT_ID: "ACCOUNT_ID_AWS"
    REPOSITORY_NAME: "REPOSITORY_NAME"
    CONTAINER_NAME: "CONTAINER_NAME"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd ./backend
      - chmod +x ./scripts/upload-container-env.sh
      - npm install
      - npm install -g dotenv-cli
  pre_build:
    commands:
      - DATABASE_URL=postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_ENDPOINT/$DATABASE_NAME
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - cd ./src/data/models
      - npx prisma generate
      - npx dotenv -v DATABASE_URL="$DATABASE_URL" -- npx prisma migrate deploy
      - cd ../../../
      - npm run test
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Updating container environment file in S3 bucket"
      - ./scripts/upload-container-env.sh
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
    base-directory: backend
