version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21.6.1
    commands:
      - echo "Install phase"

  build:
    commands:
      - cd ./backend
      - echo "Building backend"
      - npm install
      -
      - echo "Generating Prisma client"
      - cd ./src/data/models
      - npx prisma generate
      -
      - cd ../../../
      - echo "Running unit tests"
      - npm run test
      -
      - echo "Building backend..."
      - npm run build
  post_build:
    commands:
      - echo Zipping the dist folder...
      - zip -r dist.zip dist appspec.yml scripts .env.prod.aws

artifacts:
  name: backend-artifact
  files:
    - dist.zip
