version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21.6.1
    commands:
      - echo "Install phase..."

  build:
    commands:
      - echo "Building frontend..."
      - cd frontend
      - npm install
      - npm run build
      - cd ..
      - echo "Building backend..."
      - cd backend
      - npm install
      - npm run build

artifacts:
  files:
    - frontend/.next/**/*
    - backend/dist/**/*
  discard-paths: yes
