version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21.6.1
    commands:
      - echo "Install phase..."

  build:
    commands:
      - echo "Building frontend..."
      - cd ./frontend
      - npm install
      - npm run build
      - cd ..
      - echo "Generating Prisma client"
      - cd ./backend/src/data/models
      - prisma generate
      -
      - echo "Building backend..."
      - cd ../../../
      - npm install
      - npm run build

artifacts:
  files:
    - frontend/.next/**/*
    - backend/dist/**/*
  discard-paths: yes
