version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21.6.1

  pre_build:
    commands:
      - REGION_AWS=$(aws ssm get-parameter --name "REGION_AWS" --query Parameter.Value --with-decryption --output text)
      - SERVER_URL=$(aws ssm get-parameter --name "$SERVER_URL" --region "$REGION_AWS" --with-decryption --query "Parameter.Value" --output text)
      - cd ./frontend
      - printf 'NEXT_PUBLIC_SERVER_URL=%s' $SERVER_URL > .env.production

  build:
    commands:
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/out'
