version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21.6.1
    commands:
      - echo "Install phase"

  pre_build:
    commands:
      - TASK_ARN=$(aws ecs list-tasks --cluster SimpleCloudStorageCluster --service-name ScsService --query "taskArns[0]" --output text)
      - ENI_ID=$(aws ecs describe-tasks --cluster SimpleCloudStorageCluster --tasks $TASK_ARN --query "tasks[0].attachments[0].details[?name=='networkInterfaceId'].value" --output text)
      - SERVER_URL=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI_ID --query "NetworkInterfaces[0].Association.PublicIp" --output text)
      - cd ./frontend
      - printf 'NEXT_PUBLIC_SERVER_URL=http://%s' $SERVER_URL > .env.production

  build:
    commands:
      - echo "Building frontend"
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/out'
